<?php

/**
 * @file
 * Contains reservation_calendar.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reservation_calendar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reservation_calendar module.
    case 'help.page.reservation_calendar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Kalendar za rezervacije.') . '</p>';
      $output .= '<h4>' . t('Kako koristiti?') . '</h4>';
      $output .= '<ol>';
      $output .= '<li>' . t('Instalirati modul.') . '</li>';
      $output .= '<li>' . t('Otići u user profile (my account -> view profile).') . '</li>';
      $output .= '<li>' . t('Pod tabom Articles nalaze se svi artikli tog usera.') . '</li>';
      $output .= '<li>' . t('Odabrati artikl.') . '</li>';
      $output .= '<li>' . t('Na kalendaru odabrati datum rezervacije.') . '</li>';
      $output .= '</ol>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function reservation_calendar_theme() {
  return [
    'reservation_calendar' => [
      'variables' => [],
    ],
    'usercontent' => [
      'variables' => ['nodes' => [], 'user' => ''],
    ],
  ];
}
